networks:
  mynet6:
    name: ipv6net
    enable_ipv6: true
    driver: bridge

services:
  web:
    image: webssh:latest
    build: .
    container_name: ws
    ports:
      - "8888:8888"
    networks:
      - mynet6
