networks:
  mynet6:
    name: ipv6net
    enable_ipv6: true
    driver: bridge

services:
  web:
    # 存在 build 时 此为创建的镜像名；没有 build 时，此为要拉取的镜像名
    image: webssh:latest
    build: .
    container_name: ws
    ports:
      - "8888:8888"
    networks:
      - mynet6
