networks:
  mynet6:
    name: ipv6net
    enable_ipv6: true
    driver: bridge

services:
  web:
    # 如果镜像存在于 docker hub 上就会拉取（当拉取成功时，创建容器就会使用此镜像），不管上下文有没有 build 项
    # 如果 docker hub 上没有此镜像，且上下文中有 build 项，会作为即将被创建的镜像名称
    image: webssh:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ws
    restart: always
    ports:
      - "8888:8888"
    networks:
      - mynet6
