networks:
  mynet6:
    name: ipv6net
    enable_ipv6: true
    driver: bridge

services:
  webssh:
    # 如果镜像存在于 docker hub 上就会拉取（当拉取成功时，创建容器就会使用此镜像），不管上下文有没有 build 项
    # 如果 docker hub 上没有此镜像，且上下文中有 build 项，会作为即将被创建的镜像名称
    image: webssh:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ws
    restart: always
    ports:
      - "8888:8888"
    networks:
      - mynet6
  nginx:
        image: nginx:1.25-alpine
        # 映射端口 【宿主机端口:容器端口】
        ports:
            - "80:80"
            - "443:443"
        # 容器名称
        container_name: test
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        restart: always
